[package]
name = "paragraphs"
version = "0.3.1"
authors = ["Pranav Marathe <pmarathe25@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A Parallel Graph Execution Library"
repository = "https://github.com/pmarathe25/ParaGraphs"

[dependencies]
